# Generated by Django 5.0.6 on 2024-05-25 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doors', models.IntegerField(choices=[(2, '2'), (4, '4')])),
                ('year', models.DateField()),
                ('date_of_create', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='Images')),
                ('car_mark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmark')),
            ],
        ),
    ]
